import Header from './Components/Layout/Header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dentistry Decoded',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (<>

    <html lang="en">
      <body>
  <Header/>
        

          {children}
          
  
          </body>
    </html>
  </>
  )
}
